<a href="https://colab.research.google.com/github/Anisha-singh2207/PyTorch/blob/main/Video1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
print(torch.__version__)


2.6.0+cu124


Creating Tensor

In [5]:
a=torch.empty(2,3)

In [6]:
type(a)

torch.Tensor

In [7]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
#using rand
torch.rand(2,3)

tensor([[0.9171, 0.7703, 0.4420],
        [0.5602, 0.8280, 0.6549]])

In [10]:
# use of seed
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [11]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [13]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [15]:
torch.eye((5))

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [17]:
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

Tensor Shapes


In [18]:
x=torch.tensor([[1,2,3],[4,5,6]])

In [19]:
x.shape

torch.Size([2, 3])

In [20]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 1, 0]])

In [21]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [22]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

Tensor Data type


In [23]:
x.dtype

torch.int64

In [24]:
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

Scalar Operation

In [25]:
x=torch.rand(2,2)

In [26]:
x

tensor([[0.2566, 0.7936],
        [0.9408, 0.1332]])

In [27]:
x+2 # addition

tensor([[2.2566, 2.7936],
        [2.9408, 2.1332]])

In [28]:
x-2

tensor([[-1.7434, -1.2064],
        [-1.0592, -1.8668]])

In [29]:
x*2

tensor([[0.5131, 1.5873],
        [1.8815, 0.2664]])

In [30]:
x/3

tensor([[0.0855, 0.2645],
        [0.3136, 0.0444]])

In [32]:
(x*100)//3

tensor([[ 8., 26.],
        [31.,  4.]])

In [33]:
((x*100)//3)%2

tensor([[0., 0.],
        [1., 0.]])

In [34]:
x**2

tensor([[0.0658, 0.6299],
        [0.8851, 0.0177]])

Element wise opeation

In [35]:
a=torch.rand(2,3)
b=torch.rand(2,3)

In [36]:
print(a)
print(b)

tensor([[0.9346, 0.5936, 0.8694],
        [0.5677, 0.7411, 0.4294]])
tensor([[0.8854, 0.5739, 0.2666],
        [0.6274, 0.2696, 0.4414]])


In [37]:
a+b

tensor([[1.8200, 1.1675, 1.1360],
        [1.1952, 1.0107, 0.8708]])

In [38]:
a-b

tensor([[ 0.0492,  0.0197,  0.6028],
        [-0.0597,  0.4715, -0.0120]])

In [39]:
a*b

tensor([[0.8275, 0.3407, 0.2318],
        [0.3562, 0.1998, 0.1895]])

In [40]:
a/b

tensor([[1.0555, 1.0343, 3.2613],
        [0.9048, 2.7485, 0.9729]])

In [41]:
a**b

tensor([[0.9419, 0.7413, 0.9634],
        [0.7010, 0.9224, 0.6886]])

In [42]:
a%b

tensor([[0.0492, 0.0197, 0.0697],
        [0.5677, 0.2018, 0.4294]])

In [43]:
c=torch.tensor([-1,-2,3,-4])

In [44]:
#abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [45]:
torch.neg(c)

tensor([ 1,  2, -3,  4])

In [48]:
d=torch.tensor([1.9,2.3,3.7,4.4])

In [49]:
torch.round(d)

tensor([2., 2., 4., 4.])

In [50]:
#ceil
torch.ceil(d)


tensor([2., 3., 4., 5.])

In [51]:
#floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [52]:
#clamp
torch.clamp(d,min=2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

Reduction operation

In [53]:

e=torch.randint(size=(2,3),low=0,high=10)

In [54]:
e

tensor([[3, 1, 9],
        [3, 1, 9]])

In [55]:
torch.sum(e)

tensor(26)

In [56]:
# sum along columns
torch.sum(e,dim=0)

tensor([ 6,  2, 18])

In [57]:
# sum along rows
torch.sum(e,dim=1)

tensor([13, 13])

In [58]:
# mean
torch.mean(e.float())

tensor(4.3333)

In [59]:
# mean along columns
torch.mean(e.float(),dim=0)

tensor([3., 1., 9.])

In [60]:
# mean along rows
torch.mean(e.float(),dim=1)


tensor([4.3333, 4.3333])

In [61]:
# median
torch.median(e)

tensor(3)

In [62]:
# max and min
torch.max(e)
torch.min(e)

tensor(1)

In [64]:
# product
torch.prod(e)

tensor(729)

In [66]:
# sgatndard deviation
torch.std(e.float())

tensor(3.7238)

In [68]:
# variance
torch.var(e.float())

tensor(13.8667)

In [69]:
#argmax
torch.argmax(e)

tensor(2)

In [70]:
#argmin
torch.argmin(e)

tensor(1)

Matrix operations


In [71]:
f=torch.randint(size=(2,3),low=0,high=10)
g=torch.randint(size=(3,2),low=0,high=10)

In [72]:
print(f)
print(g)

tensor([[7, 9, 2],
        [0, 5, 9]])
tensor([[3, 4],
        [9, 6],
        [2, 0]])


In [73]:
# matrix multiplication
torch.matmul(f,g)

tensor([[106,  82],
        [ 63,  30]])

In [74]:
vector1=torch.tensor([1,2,3])
vector2=torch.tensor([4,5,6])

# dot product
torch.dot(vector1,vector2)

tensor(32)

In [75]:
# transpose
torch.transpose(f,0,1)

tensor([[7, 0],
        [9, 5],
        [2, 9]])

In [79]:
h=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)

In [80]:
h

tensor([[3., 4., 3.],
        [7., 0., 9.],
        [0., 9., 6.]])

In [81]:
#determinant
torch.det(h)

tensor(-222.)

In [82]:
# inverse
torch.inverse(h)

tensor([[ 0.3649, -0.0135, -0.1622],
        [ 0.1892, -0.0811,  0.0270],
        [-0.2838,  0.1216,  0.1261]])

Comparison operation

In [83]:
i=torch.randint(size=(2,3),low=0,high=10)
j=torch.randint(size=(2,3),low=0,high=10)
print(i)
print(j)

tensor([[9, 5, 4],
        [8, 8, 6]])
tensor([[0, 0, 0],
        [0, 1, 3]])


In [84]:
# greater than
i>j

tensor([[True, True, True],
        [True, True, True]])

In [85]:
# less than
i<j

tensor([[False, False, False],
        [False, False, False]])

In [86]:
# equal to
i==j

tensor([[False, False, False],
        [False, False, False]])

In [87]:
# not equal to
i!=j

tensor([[True, True, True],
        [True, True, True]])

Special Function

In [94]:
k=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
k

tensor([[3., 8., 9.],
        [3., 7., 8.]])

In [95]:
# log
torch.log(k)

tensor([[1.0986, 2.0794, 2.1972],
        [1.0986, 1.9459, 2.0794]])

In [96]:
# exp
torch.exp(k)

tensor([[  20.0855, 2980.9580, 8103.0840],
        [  20.0855, 1096.6332, 2980.9580]])

In [97]:
#sqrt
torch.sqrt(k)

tensor([[1.7321, 2.8284, 3.0000],
        [1.7321, 2.6458, 2.8284]])

In [98]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9526, 0.9997, 0.9999],
        [0.9526, 0.9991, 0.9997]])

In [99]:
# softmax
torch.softmax(k,dim=1)

tensor([[0.0018, 0.2685, 0.7297],
        [0.0049, 0.2676, 0.7275]])

In [100]:
# relu
torch.relu(k)

tensor([[3., 8., 9.],
        [3., 7., 8.]])

Implace Operations

In [101]:
m=torch.rand(2,3)
n=torch.rand(2,3)

In [102]:
m.add_(n)

tensor([[1.2968, 1.0278, 0.2707],
        [1.0130, 0.9503, 1.4092]])

In [103]:
m

tensor([[1.2968, 1.0278, 0.2707],
        [1.0130, 0.9503, 1.4092]])

In [104]:
n

tensor([[0.3813, 0.7860, 0.1115],
        [0.2477, 0.6524, 0.6057]])

Copying the tensor

In [105]:
a=torch.rand(2,3)

In [106]:
a

tensor([[0.3725, 0.7980, 0.8399],
        [0.1374, 0.2331, 0.9578]])

In [107]:
b=a

In [108]:
b

tensor([[0.3725, 0.7980, 0.8399],
        [0.1374, 0.2331, 0.9578]])

In [109]:
b=a.clone()

In [110]:
a

tensor([[0.3725, 0.7980, 0.8399],
        [0.1374, 0.2331, 0.9578]])

In [111]:
b

tensor([[0.3725, 0.7980, 0.8399],
        [0.1374, 0.2331, 0.9578]])

In [112]:
a[0][0]=10

In [113]:
a

tensor([[10.0000,  0.7980,  0.8399],
        [ 0.1374,  0.2331,  0.9578]])

In [114]:
b

tensor([[0.3725, 0.7980, 0.8399],
        [0.1374, 0.2331, 0.9578]])

Reshapping Tensors

In [117]:
a=torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [119]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [120]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [122]:
b=torch.rand(2,3,4)
b

tensor([[[0.3139, 0.4654, 0.1612, 0.1568],
         [0.2083, 0.3289, 0.1054, 0.9192],
         [0.4008, 0.9302, 0.6558, 0.0766]],

        [[0.8460, 0.3624, 0.3083, 0.0850],
         [0.0029, 0.6431, 0.3908, 0.6947],
         [0.0897, 0.8712, 0.1330, 0.4137]]])

In [123]:
# permute
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [125]:
# unsqueeze
c=torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [126]:
# squeeze
d=torch.rand(1,20)
d.squeeze(0)

tensor([0.3188, 0.8352, 0.8688, 0.0099, 0.1570, 0.5806, 0.6328, 0.9467, 0.6340,
        0.3641, 0.1591, 0.6529, 0.4636, 0.7751, 0.4205, 0.4074, 0.9638, 0.7982,
        0.2598, 0.5461])

Numpy and PyTorch

In [127]:
import numpy as np
a=torch.tensor([1,2,3])

In [128]:
a
b=a.numpy()

In [129]:
b

array([1, 2, 3])

In [130]:
type(b)

numpy.ndarray

In [131]:
c=np.array([1,2,2])

In [132]:
c

array([1, 2, 2])

In [133]:
torch.from_numpy(c)

tensor([1, 2, 2])